agent:
  name: visualize_transforms_anns_dir
  description: agent to read from a given folder, performing horizontal flip, electric transform  and rotation transforms, and saving the resulting image in a given folder

templates:
- template_name: InputTemplate
  class_name: InputTemplate
  template_input: null
  attributes: {}

- template_name: HorizontalFlip
  class_name: HorizontalFlipWrapper
  template_input: InputTemplate
  attributes:
    horizontalflip_init:
      p: 1.0

- template_name: ElasticTransform
  class_name: ElasticTransformWrapper
  template_input:  HorizontalFlip
  attributes:
    elastictransform_init:
      mask_value: 150
      p: 1.0
      alpha: 100
      sigma: 50

- template_name: Rotate
  class_name: RotateWrapper
  template_input: ElasticTransform
  attributes:
    rotate_init:
      limit: [-45, 45]
      interpolation: 1
      border_mode: 4
      value: [0, 0, 0]
      mask_value: null
      rotate_method: "largest_box"
      crop_border: false
      fill_value: 0
      mask_fill_value: 0
      deterministic: true
      p: 1.0
