services:
  sinapsis-image-transforms: &default
    image: sinapsis-image-transforms:base
    container_name: sinapsis-image-transforms-main
    build:
      context: ../
      dockerfile: docker/Dockerfile
      ssh:
        - default
    shm_size: '8gb'
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /lib/python3.10/:/app/.venv/lib/python3.10/site-packages
      GRADIO_SHARE_APP: ${GRADIO_SHARE_APP:-false}
    network_mode: "host"

