services:

  sinapsis-albumentations-inference:
    extends:
      service: sinapsis-image-transforms
      file: compose.yaml
    container_name: sinapsis-albumentations-inference
    volumes:
      - "../packages/sinapsis_albumentations/src/sinapsis_albumentations/configs/:/app/src/sinapsis_albumentations/configs/"
      - "../webapps/:/app/webapps"
    command: /app/.venv/bin/sinapsis run src/sinapsis_albumentations/configs/visualize_transforms_with_anns_from_dir.yml

  sinapsis-albumentations-gradio:
    extends:
      service: sinapsis-image-transforms
      file: compose.yaml
    container_name: sinapsis-albumentations-inference-gradio
    command: python3 webapps/gradio_albumentations_transforms_visualizer.py